name: alsf-rrp
channels:
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - fastp=1.0.1=heae3180_0
  - isa-l=2.31.1=hb9d3cd8_1
  - libdeflate=1.25=h17f619e_0
  - libgcc=15.2.0=h767d61c_7
  - libgomp=15.2.0=h767d61c_7
  - libstdcxx=15.2.0=h8f9b012_7
prefix: /home/mgower/miniforge3/envs/alsf-rrp
